menu:
    Archives: /archives/
    Links: /links/
    About: https://xiaopc.org/about/
    Rss: /atom.xml
    CN: https://xiaopc.org/

favicon: /favicon.ico
logo: /logo.png
avatar: /avatar.jpg
likeqr: /wechat_like.png

# Comment
# e.g disqus: seansun
disqus: xiaopc-1
duoshuo:

# Analytics
# google-analytics:
ga: UA-23646862-3

# Copyright Infomation
startyear: 2008
