menu:
    Archives: /archives/
    Links: /links/
    About: https://xpc.im/
    Rss: /atom.xml
    CN: https://xiaopc.org/

favicon: /favicon.ico
logo: /logo.png
avatar: /avatar.jpg
likeqr: /wechat_like.png

# Comment
# e.g disqus: seansun
disqus: xiaopc-1
duoshuo:

# Analytics
# google-analytics:
ga: G-KNHBVTCZSN

# google-tag-manager
gtm:

# Copyright Infomation
startyear: 2008
